services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - redis-network
  tama-backend:
    image: "tama-backend:latest"
    container_name: "tama-backend"
    ports:
      - "8080:8080"
    networks:
      - redis-network
  tama-ui:
    image: "tama-ui:latest"
    container_name: "tama-ui"
    ports:
      - "3000:3000"
    networks:
      - redis-network
  tama-care:
    image: "tama-care:latest"
    container_name: "tama-care"
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge
